'use client';

import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Cairo } from "next/font/google";
import { usePathname } from "next/navigation"; // Import the usePathname hook
import "./globals.css";

const cairo = Cairo({ subsets: ["latin"] });

// export const metadata = {
//   title: "Naser's Academy Platform",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); 


  const hideHeaderFooter = pathname === "/sign-in" || 
   pathname === "/sign-up" ||
    pathname === "/Forget-pass"
  || pathname === "/Rest-pass"
  || pathname === "/verify-code"
  || pathname === "/Success-reg";

  return (
    <html lang="en">
      <body className={`cairo-font ${cairo.className}`}>
        {!hideHeaderFooter && <Header />}
        {children}
        {!hideHeaderFooter && <Footer />}
      </body>
    </html>
  );
}
