

import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Naser's academy Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <html lang="en" >
          <body className={`cairo-font ${cairo.className}`}>
            {children}
          </body>
        </html>
  );
}
